version: 2
jobs:
  build:
    docker:
      - image: mankitpong/happygo:latest
    working_directory: /happygo
    steps:
      - run: git pull
      - run: bazel build --define=grpc_no_ares=true //mcts:mcts_main
      - run: bazel build --define=grpc_no_ares=true //mcts:debug_tool
      - run: bazel build --define=grpc_no_ares=true //dist:dist_zero_model_server